# Generated by Django 5.1.4 on 2025-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostschema',
            name='img_data',
            field=models.ImageField(blank=True, null=True, upload_to='blogpost_images/'),
        ),
    ]
